### ISSUE TITLE
malloc error in taup get_travel_times for certain Mars nd format models

### ISSUE THREAD

**Issue by mpanning** [obspy/obspy#1639]
obspy version: 1.0.2
Python version: 2.7.12
Platform: OS X 10.12.2 using macports python and obspy ports

For certain distances, the get_travel_times method fails causing the script to crash with no Python error with the following error message:

> Python(66056,0x7fffebf493c0) malloc: *** error for object 0x7fe21140ea88: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
Abort

However, after adding a print statement into my script within the try-except construction that is calling get_travel_times, the code fails with a Segmentation Fault.  I assume this is a problem in some non-python portion of the taup package, but I have not yet attempted to debug further.

I'm attaching a python zip file with a python script which generates the failure (plot_travel_times.py), as well as 2 model files (DWThot.nd and EH45Tcold.nd).  The first one fails unpredictably at distances between 64 and 67 degrees, while the second model proceeds to completion. Both models actually have a completely fluid core, and include a dummy layer at the end of the file with inner-core named discontinuity at the planet center. 

I'm also including the npz files generated, but these can be moved to another directory, and the script will use taup.taup_create.build_taup_model to make a new npz file.

The script expects an argument with the input model file, and a second optional argument with an output file name (which defaults to tt.png).

[obspy_taup_error.zip](https://github.com/obspy/obspy/files/697198/obspy_taup_error.zip)

**Comment by krischer** [comment]
Both of these issues are already fixed in the `master` or `maintenance_1.0.x` branches. I confirm that both errors also happen on my machine with `1.0.2`.

Still - this does not mean that the travel times are correct. The hot one looks weird. Why should it have an S-wave shadow zone at those epicentral distances?

It might be that the phase naming scheme just breaks down if some assumptions about Earth are no longer fulfilled? Do you know how the Java TauP handles these models?

**DWThot:** ![dwthot](https://cloud.githubusercontent.com/assets/800487/21829970/e469fa62-d799-11e6-957f-a8634cbccc4d.png)

**EH45Tcold:** ![eh45tcold](https://cloud.githubusercontent.com/assets/800487/21829971/e46ae35a-d799-11e6-9af1-7478225075b3.png)

**Comment by krischer** [comment]
Reference travel times for example through ray tracing would be very useful to have!

**Comment by martinvandriel** [comment]
The hot model has a little bit of an s-wave LVL in the flat earth transform, while the cold one doesn't. So it could be true, but I am a bit surprised by the width of the shadow zone. Can you plot the raypaths? Otherwise, TTBox by Martin Knappmeyer should be a working reference, but I have not used it myself.


![figure1](https://cloud.githubusercontent.com/assets/2306288/21841688/988a575a-d7e3-11e6-8509-77d264351c64.png)

![figure2](https://cloud.githubusercontent.com/assets/2306288/21841752/f9d7a800-d7e3-11e6-9b72-8e640b474dfd.png)

**Comment by krischer** [comment]
So bad (or good? don't know if this really is an error but it looks fishy) news first. The latest Java TauP release shows the same issue:

![screen shot 2017-01-11 at 15 08 36](https://cloud.githubusercontent.com/assets/800487/21851578/fa759570-d80f-11e6-9df6-cbc4f18dd4a0.png)

@crotwell: Do you by chance have any intuition what's happening here?

Raypaths with the ObsPy version (don't know how to make these fan plots with the Java version in an easy way). IMHO there is clearly some problem here.

**DWTHot - P waves:**
![dwthot_p](https://cloud.githubusercontent.com/assets/800487/21851617/2b634664-d810-11e6-9c02-10f0a851c621.png)

**DWTHot - S waves:**
![dwthot_s](https://cloud.githubusercontent.com/assets/800487/21851618/2f5b3b96-d810-11e6-9ee1-96962e89db33.png)

**EH45TCold - P waves:**
![eh45tcold_p](https://cloud.githubusercontent.com/assets/800487/21851629/38951e02-d810-11e6-9dcb-dbed7e47a117.png)

**EH45TCold - S waves:**
![eh45tcold_s](https://cloud.githubusercontent.com/assets/800487/21851632/3cf9dda2-d810-11e6-9948-5000b0d1b815.png)

**Comment by crotwell** [comment]
First question, just to be clear, this is not a model of the earth? Your planet radius is only 3389.5, which is fine as long as that is what you meant. Mars I am guessing.
 
Second, guessing how a low velocity zone will behave is tricky, but looking at the model I am not really surprised at a large shadow zone. TauP thinks that the LVZ covers about 90 km in depth, which given the small radius and slow gradient with depth below, is substantial.

A quote I like is "Intuition in elastodynamics is a dangerous thing", but here is a back of the envelope calculation that gives a feel for how badly behaved the LVZ can be. Imagine that instead of a decreasing velocity in the LVZ we have a constant velocity over that 90 km in depth, starting at 3300 and going down to 3210 km radius. The straight line path that just grazes the lower radius is allowed and the additional distance for the ray over the ray that turns just above this layer would be about:
```
2* acos(3210/3300) ~= 27 deg
```

That doesn't look too far off of what you show in your ray plot, so I am inclined to think it is right. You will have a retrograde segment that would tend to make it smaller, but also the model has an actual decrease in velocity with depth, which would tend to make it larger, but as a quick guess a about 30 deg shadow is probably not a bad estimate.

That said, there is always the chance that I have a bug in the code, but unless you can give me more details as to why you think this is incorrect, I would probably say the output is probably ok. But please do let me know if you come up with a more detailed argument as to why this is not the correct output and I will dig in more.

Philip

**Comment by mpanning** [comment]
Looks like TTBox is consistent.  Here's the P and S travel time curves for TTBox with 0.01 degree takeoff angle resolution.  There really is a very large shadow zone for S, but not P.  I think taup is working fine aside from the malloc/segmentation faults which are apparently already corrected.

![dwthot_ttc](https://cloud.githubusercontent.com/assets/14908499/21855839/c8a98212-d7ed-11e6-98e3-9fd8a4aa8f33.png)

**Comment by mpanning** [comment]
I've verified also that the errors are gone when I'm using the `master` branch instead of 1.0.2, so I think we can consider this issue resolved with no additional coding necessary, given that the calculations appear consistent against a TTBox benchmark.

**Comment by megies** [comment]
Ok, closing this issue. Feel free to reopen if necessary.

**Comment by krischer** [comment]
@crotwell Thanks a lot for the intuitive explanation - that does make sense! I still have some problems understanding how these oddly "refracted" rays that pass just under the surface of the shadow zone work but that might just be a raypath calculation issue.

@mpanning Can you send me the results of the TTBox calculations? Then I can add a new test against an independent code which is always nice.

**Comment by mpanning** [comment]
[Mars_model_test.zip](https://github.com/obspy/obspy/files/702200/Mars_model_test.zip)

I'm not particularly familiar with TTBox, so I'm not sure how to quickly get it to a useful ASCII file output, so I'm just passing on some matlab files.  This was created with the version of TTBox downloaded from [Martin Knapmeyer's website](http://www.dlr.de/pf/en/desktopdefault.aspx/tabid-4880/8104_read-36233/).  The nd format used in the code differs slightly in that it requires some keyword lines at the beginning, which are included in the zipfile as DWThot_TTBox.nd and EH45Tcold_TTBox.nd.  The travel time curves were produced using the following lines in Matlab 2016b after adding the TTBox folder to the Matlab path

`h=0`
`dangle=0.01`
`phases=strvcat('P', 'S')`
`model=mkreadnd('DWThot_TTBox.nd')`
`ttc=mkttcurves(model,h,dangle,phases)`
`mkplotttcurves(ttc,'-or')`

All workspace variables were saved into the included Matlab `.mat` files in the zip archive, and the `ttc` variable is a structure containing all the relevant phase name, ray parameter, and phase name information.  It's documented in the html documentation included with the package download at the website listed above.  I also included `png` versions of the figures produced by the mkplotttcurves command above.

**Comment by megies** [comment]
Looks like there's still quite some open questions about this one, how about we punt this to 1.1.0 or even 1.1.1?

**Comment by megies** [comment]
No feedback, punting this to 1.1

**Comment by krischer** [comment]
Sure - this is actually no bug but would just result in an additional test. I'll eventually get to it ;-)

**Comment by megies** [comment]
Since this is talking about malloc issues, this is from the days of using iaspei-tau with Fortran wrapper before switching to a Python port of java taup, so this isn't really relevant anymore. CC @johnrudge
